title: Gabriel Rodriguez Perez
#logo: /assets/img/Headshot.jpg
description: Full Stack Software Developer. Get to know more about me, my skills and background in Software Development.
linkedin_url: https://www.linkedin.com/in/glrodriperez
github_url: https://github.com/glrodriperez98
show_downloads: false
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
